#!/bin/bash
dirname="$1_dir"
filename="$1.txt"

echo "filename is $filename"

if [ -d $dirname ]; then
	:
  else
	mkdir $dirname
fi

if [ -d $dirname/songs ]; then
	:
  else
    mkdir $dirname/songs
fi

if [ -d $dirname/graphs ]; then
	:
  else
	mkdir $dirname/graphs
fi

echo vagalume [start]
python3 main.py $dirname < $filename
echo vagalume [done]

echo " "

echo graph [start]
python3 graph.py $dirname
echo graph [done]

echo " "

echo repCount [start]
python3 repCount.py $dirname
echo repCount [done]

# ./clean
