#!/bin/bash

if [ -d songs ]; then
	:
  else
    mkdir songs
fi

if [ -d graphs ]; then
	:
  else
	mkdir graphs
fi

echo vagalume [start]
python3 main.py < songs.txt
echo vagalume [done]

echo " "

echo graph [start]
python3 graph.py
echo graph [done]

echo " "

echo repCount [start]
python3 repCount.py
echo repCount [done]

# ./clean
